# Which version of Docker compose we're using
version: "3"

# Listing out the multiple containers
services:
  # This is the nodejs app
  app:
    # Name of the container
    container_name: urghbot-node
    build:
      # Context = directory containing the Dockerfile
      context: app
      dockerfile: Dockerfile
    # Environment variables
    env_file: .env
    environment:
      - MONGODB_URGHBOT_URI=$MONGODB_URGHBOT_URI
      - TWITCH_BOT_USERNAME=$TWITCH_BOT_USERNAME
      - TWITCH_BOT_PASSWORD=$TWITCH_BOT_PASSWORD
      - TWITCH_BOT_CLIENT_ID=$TWITCH_BOT_CLIENT_ID
      - TWITCH_BOT_CLIENT_SECRET=$TWITCH_BOT_CLIENT_SECRET
    # The nodejs app depends on the 'db' container
    depends_on:
      - db
    # Mounted volumes for the application
    volumes:
      - ./app:/app
    working_dir: /app
  # This is the mongodb container
  db:
    # Name of the container once its built
    container_name: urghbot-mongo
    image: mongo
    restart: always
    # Port forwarding 27017 (default for mongo)
    ports:
      - 27017:27017
    # Binding './db' path to Mongo's data location in the container ("/data/db")
    volumes:
      - ./db:/data/db
